# Database configuration for team_game_logs DAG
DB_SCHEMA = 'nba'

TEAM_GAME_LOGS_TABLE = {
    'name': 'team_game_logs',
    'columns': {
        'SEASON_YEAR': 'VARCHAR(10)',
        'TEAM_ID': 'INTEGER',
        'TEAM_ABBREVIATION': 'VARCHAR(10)',
        'TEAM_NAME': 'VARCHAR(50)',
        'GAME_ID': 'VARCHAR(20)',
        'GAME_DATE': 'DATE',
        'MATCHUP': 'VARCHAR(50)',
        'WL': 'VARCHAR(2)',
        'MIN': 'INTEGER',
        'FGM': 'INTEGER',
        'FGA': 'INTEGER',
        'FG_PCT': 'FLOAT',
        'FG3M': 'INTEGER',
        'FG3A': 'INTEGER',
        'FG3_PCT': 'FLOAT',
        'FTM': 'INTEGER',
        'FTA': 'INTEGER',
        'FT_PCT': 'FLOAT',
        'OREB': 'INTEGER',
        'DREB': 'INTEGER',
        'REB': 'INTEGER',
        'AST': 'INTEGER',
        'TOV': 'INTEGER',
        'STL': 'INTEGER',
        'BLK': 'INTEGER',
        'BLKA': 'INTEGER',
        'PF': 'INTEGER',
        'PFD': 'INTEGER',
        'PTS': 'INTEGER',
        'PLUS_MINUS': 'FLOAT',
        'GP_RANK': 'INTEGER',
        'W_RANK': 'INTEGER',
        'L_RANK': 'INTEGER',
        'W_PCT_RANK': 'INTEGER',
        'MIN_RANK': 'INTEGER',
        'FGM_RANK': 'INTEGER',
        'FGA_RANK': 'INTEGER',
        'FG_PCT_RANK': 'INTEGER',
        'FG3M_RANK': 'INTEGER',
        'FG3A_RANK': 'INTEGER',
        'FG3_PCT_RANK': 'INTEGER',
        'FTM_RANK': 'INTEGER',
        'FTA_RANK': 'INTEGER',
        'FT_PCT_RANK': 'INTEGER',
        'OREB_RANK': 'INTEGER',
        'DREB_RANK': 'INTEGER',
        'REB_RANK': 'INTEGER',
        'AST_RANK': 'INTEGER',
        'TOV_RANK': 'INTEGER',
        'STL_RANK': 'INTEGER',
        'BLK_RANK': 'INTEGER',
        'BLKA_RANK': 'INTEGER',
        'PF_RANK': 'INTEGER',
        'PFD_RANK': 'INTEGER',
        'PTS_RANK': 'INTEGER',
        'PLUS_MINUS_RANK': 'INTEGER',
        'AVAILABLE_FLAG': 'INTEGER',
        'created_at': 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP'
    }
} 